services:
  - type: web
    name: scoriq-backend
    runtime: python
    plan: free
    region: frankfurt
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DATABASE_URL
        sync: false
      - key: ODDS_API_KEY
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
